import cv2
o=cv2.imread("lena.bmp",cv2.IMREAD_UNCHANGED)
kernel1 = cv2.getStructuringElement(cv2.MORPH_RECT, (25,25))
kernel2 = cv2.getStructuringElement(cv2.MORPH_CROSS,  (25,25))
kernel3 = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,  (25,25))
dst1 = cv2.dilate(o,kernel1)
dst2 = cv2.dilate(o,kernel2)
dst3 = cv2.dilate(o,kernel3)
cv2.imshow("orriginal",o)
cv2.imshow("RECT",dst1)
cv2.imshow("CROSS",dst2)
cv2.imshow("ELLIPSE",dst3)
cv2.waitKey()
cv2.destroyAllWindows()